spring :
    datasource :
        url : jdbc:mariadb://localhost:3306/kakaostyle
        username : root
        password : 1
        
    jpa :   
        hibernate :
            ddl-auto : update  
        generate-ddl: true # true 설정 시, 해당 데이터를 근거로 서버 시작 시점에 DDL 문 생성하여 DB 에 적용 (ddl 생성옵션 링크) 
        show-sql: true # true 설정 시, 콘솔에 JPA 쿼리를 보여준다. 
        defer-datasource-initialization: true


    sql : 
      init : 
       data-locations: classpath*:templates/data.sql